services:
  studio:
    networks:
      - traefik
    labels:
      traefik.enable: 'true'
      traefik.docker.network: ${BLOG_STUDIO_TRAEFIK_NETWORK:-home-server_default}
      traefik.http.routers.blog-studio.entrypoints: websecure
      traefik.http.routers.blog-studio.rule: Host(`${BLOG_STUDIO_HOSTNAME:-blog-editor.internal.wj2015.com}`)
      traefik.http.routers.blog-studio.tls: 'true'
      traefik.http.routers.blog-studio.service: blog-studio
      traefik.http.services.blog-studio.loadbalancer.server.port: '4310'

networks:
  traefik:
    external: true
    name: ${BLOG_STUDIO_TRAEFIK_NETWORK:-home-server_default}
